# Generated by Django 4.2.27 on 2025-12-15 15:30

import byabulimi.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('language_code', models.CharField(default='lug', help_text="Preferred language (e.g., 'lug', 'swa')", max_length=5)),
                ('region', models.CharField(blank=True, help_text='Used for localized weather/market alerts', max_length=100, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=byabulimi.models.query_image_upload_path)),
                ('raw_query_text', models.TextField(blank=True, null=True)),
                ('detected_crop', models.CharField(default='Unknown', max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='byabulimi.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='byabulimi.query')),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('localized_advice', models.TextField(help_text='The final, localized treatment/prevention text.')),
                ('is_expert_referred', models.BooleanField(default=False)),
                ('gemini_prompt', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
