# Generated by Django 4.2.27 on 2025-12-28 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('byabulimi', '0002_farmer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
            ],
            options={
                'ordering': ['district', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(default=1, help_text='Link to the Django User account for authentication', on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('source', models.CharField(help_text='e.g., open-meteo, nasa-power, unma-scrape', max_length=50)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this cache entry should be considered stale', null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='byabulimi.localmarket')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('avg_temp_c', models.FloatField(help_text='Average temperature in Celsius', validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(60.0)])),
                ('avg_humidity', models.FloatField(help_text='Average percentage humidity', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_monthly', models.JSONField(blank=True, help_text='Optional JSON of monthly averages', null=True)),
                ('current_season', models.CharField(help_text='e.g., First Rains, Dry Season', max_length=50)),
                ('pest_warning', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'District Weather Data',
                'ordering': ['district_name'],
                'indexes': [models.Index(fields=['district_name'], name='byabulimi_d_distric_c65a6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrowdsourcedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('report_type', models.CharField(choices=[('rain', 'Heavy Rain'), ('dry', 'Dry / No Rain'), ('storm', 'Storm / Wind Damage')], max_length=20)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='byabulimi.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='byabulimi.localmarket')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('market', 'product_name', 'unit')},
            },
        ),
    ]
